all:
	pdflatex example_thesis.tex && bibtex example_thesis.aux && pdflatex example_thesis.tex && pdflatex example_thesis.tex && xdg-open example_thesis.pdf

compile:
	pdflatex example_thesis.tex && bibtex example_thesis.aux && pdflatex example_thesis.tex && pdflatex example_thesis.tex

open:
	xdg-open example_thesis.pdf
